services:
  postgres:
    image: postgres:15.3
    container_name: ecs-demo-postgres
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    volumes:
      - ecs_demo_postgres_volume:/var/lib/postgresql/data/
      - ./docker/postgres:/docker-entrypoint-initdb.d

volumes:
  ecs_demo_postgres_volume:
